version: "3"

services:
  app:
    build: .
    image: gabrielsclimaco/recycling-machine-backend:latest
    links:
      - rethink
    volumes:
      - ./src:/app/src
      - ./.eslintrc.js:/app/.eslintrc.js
      - ./package.json:/app/package.json
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=rethink
      - NODE_ENV=development
    depends_on:
      - rethink
  rethink:
    image: rethinkdb:latest
    expose:
      - "8080"
    ports:
      - "28015:28015"
      - "8087:8080"
    volumes:
      - db:/data

volumes:
  db: {}
